- name: rollback - Override provided OSPF V2 configuration
  hosts: switch2
  
  tasks:

  - name: rollback - Configure Ospfv2 for switch2 at Interface level
    cisco.nxos.nxos_ospf_interfaces:
      config:
        - name: Ethernet1/1
          address_family:
          - afi: ipv4
            processes:
            - process_id: "1"
              area:
                area_id: '0.0.0.0'
      state: deleted