- name: Override provided OSPF V2 configuration
  hosts: switch2
  
  tasks:

  - name: Ensure ospf is enabled for switch2
    cisco.nxos.nxos_feature:
      feature: ospf
      state: enabled

  - name: Ensure OSPF process is configured for switch2
    cisco.nxos.nxos_ospfv2:
      config:
        processes:
        - process_id: 1
          router_id: 5.5.5.5
      state: replaced

  - name: Configure Ospfv2 for switch2 at Interface level
    cisco.nxos.nxos_ospf_interfaces:
      config:
        - name: Ethernet1/1
          address_family:
          - afi: ipv4
            processes:
            - process_id: "1"
              area:
                area_id: '0.0.0.0'
      state: replaced