- name: Configure direct interface parameters in asa
  hosts: asa
  gather_facts: no

  tasks:

  - name: configure Interface GigabitEthernet0/0 in asa
    cisco.asa.asa_config:
      lines:
      - ip address 192.168.3.1 255.255.255.0
      - nameif outside
      - security-level 0
      - no shutdown
      parents: [interface GigabitEthernet0/0]

  - name: configure Interface GigabitEthernet0/1 in asa
    cisco.asa.asa_config:
      lines:
      - ip address 192.168.4.1 255.255.255.0
      - nameif inside
      - security-level 100
      - no shutdown
      parents: [interface GigabitEthernet0/1]