- name: Configure direct interface parameters in router1
  hosts: router1

  tasks:

  - name: bring interface GigabitEthernet2 to admin UP state in router1
    cisco.ios.ios_interfaces:
      config:
      - name: GigabitEthernet2
        description: Configured and Replaced by Ansible cisco.ios.ios_interfaces
        enabled: yes
      state: replaced

  - name: configure the ipv4 address of GigabitEthernet2 in router1
    cisco.ios.ios_l3_interfaces:
      config:
      - name: GigabitEthernet2
        ipv4:
        - address: 192.168.0.1/24
      state: replaced

  - name: bring interface GigabitEthernet3 to admin UP state in router1
    cisco.ios.ios_interfaces:
      config:
      - name: GigabitEthernet3
        description: Configured and Replaced by Ansible cisco.ios.ios_interfaces
        enabled: yes
      state: replaced

  - name: configure the ipv4 address of GigabitEthernet3 in router1
    cisco.ios.ios_l3_interfaces:
      config:
      - name: GigabitEthernet3
        ipv4:
        - address: 192.168.1.1/24
      state: replaced