- name: Network Getting Started First Playbook for switches
  gather_facts: false
  hosts: switch*
  tasks:
    - name: Gather all nxos facts
      cisco.nxos.nxos_facts:
    - name: Display the config
      debug:
        msg: "The hostname is {{ ansible_net_hostname }} and the OS is {{ ansible_net_version }}"