- name: Network Getting Started First Playbook for asa
  gather_facts: false
  hosts: asa
  tasks:
    - name: Gather all asa facts
      cisco.asa.asa_facts:
    - name: Display the config
      debug:
        msg: "The hostname is {{ ansible_net_hostname }} and the OS is {{ ansible_net_version }}"