- name: Delete device configuration
  hosts: localhost
  connection: local
  gather_facts: no
 
  tasks:
  - name: NSO global variables
    include_vars:
      file: nso.yaml
      name: nso

  - name: Delete configuration data
    nso_config:
      url: "{{ nso.url }}"
      username: "{{ nso.username }}"
      password: "{{ nso.password }}"
      data:
        tailf-ncs:devices:
          device:
          - name: "{{ device }}"
            tailf-ncs:config:
              junos:configuration:
                system:
                  name-server:
                  - name: 10.10.10.1
                    __state: absent
