- name: Show
  hosts: localhost
  connection: local
  gather_facts: no
 
  tasks:
  - name: Load variables
    include_vars:
      file: nso.yaml
      name: nso

  - name: Show devices config (no operational data)
    nso_show:
      url: "{{ nso.url }}"
      username: "{{ nso.username }}"
      password: "{{ nso.password }}"
      path: "/ncs:devices/device"
      operational: false
    register: result

  - name: Display the result
    debug:
      var: result
