all:
  children:
    cisco:
      hosts:
        router1: 
          ansible_host: 192.168.4.1
          ansible_network_os : ios
      vars:
        ansible_os: cisco
        ansible_connection: httpapi
        ansible_user: cisco
        ansible_password: cisco
        ansible_netconf_password: cisco
        
